### PR TITLE
Ran pdk convert and related updates

### PR DESCRIPTION
**Pull request by genebean**
Additional updates include:
- switching the base Vagrant box to genebean/centos-7-puppet-latest
- configuring .sync.yml to install the extra linters used before
- switching the Coveralls config to the one recommended by Puppet
  - this doesn't work... looking into why

@thespain I think I have gotten all the things we really care about ported over from our old testing setup to this one... what do you think?

### CODE REVIEW

**Comment by genebean** [comment]
@thespain btw... tests are passing :)

**Comment by yachub** [comment]
Wow, this looks great I should have thought of bringing it up to spec with PDK! I'll go ahead and squash commits in #13

**Review by yachub — APPROVED** [review]

**Comment by genebean** [comment]
@thespain I need your eyes on this. Please see if there are any aspects of the old Rakefile or other things it still needs. I just realized while typing this that the Vagrant setup might need adjusting. As a side note, the Coveralls integration is not working but I'll deal with it separately.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yachub** [comment]
It looks like there is no longer a `tests` rake task, so in vagrant you can manually run `bundle exec rake check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint spec` We could either add a task using [PDK extras or rakelib](https://github.com/puppetlabs/pdk-templates#rakefile), but I'm kind of leaning towards just replacing `spec_prep` with the entire line above in the vagrant file. What do you think?

Also, in `.travis.yml`, do we want to keep `DEPLOY_TO_FORGE=yes` and add username and encrypted password, or keep using puppet-blacksmith?

**Comment by genebean** [comment]
As far as the tests, I'd say we just install the PDK in the Vagrant box and then run `pdk validate ; pdk test unit`

As for the Forge deploy, let's cross that after the Puppet Contributor Summit 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
