### PR TITLE
add inputfile capability

### PR DESCRIPTION
**Pull request by egouraud**

### CODE REVIEW

**Comment by genebean** [comment]
Testing your code today... should be able to merge extremely soon. Thanks for the contribution!

**Comment by genebean** [comment]
FWIW, I released v1.2.1 a few minutes ago that added your feature along with some additional ones.

**Comment by egouraud** [comment]
thanks for the merge ;)
We will probably work on it to add more capabilities for Linux
cheers,

**Comment by genebean** [comment]
Just out of curiosity, what use case do you have for it on Linux?

**Comment by egouraud** [comment]
we have chosen a unique tool (windows, linux) to ship logs from servers to our ELK platform

**Pull request merged**
