### PR TITLE
Adding options for outputs (e.g OutputType GELF_TCP)

### PR DESCRIPTION
**Pull request by jaimeviloria**

### CODE REVIEW

**Comment by genebean** [comment]
@cerealcake - would you mind adding tests for this?

**Comment by jaimeviloria** [comment]
of course, I will add them

**Comment by jaimeviloria** [comment]
Hi Gene, the tests are present.  Please inform me if anything more is required and I will look into it.

**Comment by genebean** [comment]
Sorry for the long delay... life got in the way of coding like it does sometimes. The new version should be on the forge now. Thanks for the contribution!

**Pull request merged**
